// Generated by CoffeeScript 1.6.3
(function() {
  var User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  User = require('./user');

  module.exports = function(init) {
    return function(req, res, next) {
      if (req.user != null) {
        __extends(req.user, User);
        init(req.user);
      }
      return next();
    };
  };

}).call(this);
