// Generated by CoffeeScript 1.6.3
(function() {
  var validateObject;

  validateObject = function(obj, values) {
    var property, value;
    for (property in values) {
      value = values[property];
      if (obj[property] !== value) {
        return false;
      }
    }
    return true;
  };

  module.exports = {
    _authzConditions: {},
    grant: function(action, condition) {
      if (condition == null) {
        condition = true;
      }
      return this._authzConditions[action] = condition;
    },
    can: function(action, obj) {
      var condition;
      condition = this._authzConditions[action];
      return !!(function() {
        switch (typeof condition) {
          case 'function':
            return condition(obj);
          case 'object':
            return validateObject(obj, condition);
          default:
            return condition;
        }
      })();
    }
  };

}).call(this);
