// Generated by CoffeeScript 1.6.3
(function() {
  var app, authz, connect, http;

  http = require('http');

  connect = require('connect');

  authz = require('../index');

  app = connect();

  app.use(function(req, res, next) {
    req.user = {
      id: 1,
      name: "John"
    };
    return next();
  });

  app.use(authz(function(user) {
    user.grant('article.read');
    user.grant('article.edit', {
      authorId: user.id
    });
    return user.grant('article.delete', function(article) {
      return article.authorId === user.id && article.title === '';
    });
  }));

  app.use(function(req, res) {
    var emptyArticle, othersArticle, ownArticle, test, tests, value;
    ownArticle = {
      title: "Caterpillar Express",
      authorId: 1
    };
    othersArticle = {
      title: "Blue Note",
      authorId: 2
    };
    emptyArticle = {
      title: "",
      authorId: 1
    };
    tests = {
      "can read others articles?": req.user.can('article.read', othersArticle),
      "can edit own articles?": req.user.can('article.edit', ownArticle),
      "can edit others articles?": req.user.can('article.edit', othersArticle),
      "can delete titled articles?": req.user.can('article.delete', ownArticle),
      "can delete untitled articles?": req.user.can('article.delete', emptyArticle)
    };
    for (test in tests) {
      value = tests[test];
      res.write("" + test + " " + value + "\n");
    }
    return res.end();
  });

  http.createServer(app).listen(3000);

}).call(this);
